### ISSUE TITLE
When Reload collection view cell are overlaping.

### ISSUE THREAD

**Issue by jrkiosdev** [henrytkirk/HTKDragAndDropCollectionViewLayout#4]
I have one table-view and i am adding the object to the Array form that table view and When i trying to reload collection view data. the cells are overlapping each other.
please help me.

**Comment by henrytkirk** [comment]
Sorry for delay. I tested - you are correct. I'm pushing a fix now.

**Comment by henrytkirk** [comment]
Fixed in commit 520987d676a027940fc13ec0498a20869eeb8320
