### ISSUE TITLE
userDidEndDraggingCell - update datasource not working

### ISSUE THREAD

**Issue by AleyRobotics** [henrytkirk/HTKDragAndDropCollectionViewLayout#7]
Sample application have a bug

- (void)userDidEndDraggingCell:(UICollectionViewCell *)cell {
    [super userDidEndDraggingCell:cell];
    
    HTKDragAndDropCollectionViewLayout *flowLayout = (HTKDragAndDropCollectionViewLayout *)self.collectionView.collectionViewLayout;
     NSLog(@"%s %@",__PRETTY_FUNCTION__, self.collectionView.collectionViewLayout);//self.collectionView.collectionViewLayout = NIL!!!!
    // Save our dragging changes if needed
    if (flowLayout.finalIndexPath != nil) {
        // Update datasource
        NSObject *objectToMove = [self.dataArray objectAtIndex:flowLayout.draggedIndexPath.row];
        [self.dataArray removeObjectAtIndex:flowLayout.draggedIndexPath.row];
        [self.dataArray insertObject:objectToMove atIndex:flowLayout.finalIndexPath.row];
    }
}

LOG:
start drag first item
-[HTKDragAndDropCollectionViewLayout prepareLayout] set finalIndexPath = nil and draggedIndexPath = nil
dragging over item
-[HTKDragAndDropCollectionViewLayout insertDraggedItemAtIndexPath:] set OK finalIndexPath.row = 0
release touch
-[HTKDragAndDropCollectionViewLayout prepareLayout] set finalIndexPath = nil and draggedIndexPath = nil
-[HTKDragAndDropCollectionViewLayout resetDragging] set finalIndexPath = nil and draggedIndexPath = nil
-[HTKSampleCollectionViewController userDidEndDraggingCell:]
We never go in to if for updating datasource

**Comment by henrytkirk** [comment]
Good catch! Thanks! - Fixed in commit c6f162abc50a626fb50cbbc898a6a9f0ead75774
