### ISSUE TITLE
Doesn't perform cell dragging properly on scrollview events

### ISSUE THREAD

**Issue by gerchicov-bp** [henrytkirk/HTKDragAndDropCollectionViewLayout#8]
For example, I want to place the first element on the 10th place. So I need to make long press gesture on it and scroll to the appropriate place. But it seems it allows to move the cell to nearby places only

**Comment by henrytkirk** [comment]
Make sure you are implementing the method scrollIfNeededWhileDraggingCell: in HTKDragAndDropCollectionViewController class. When dragging an item towards bottom, it will auto-scroll.
